{% set version = "1.0.4" %}

package:
  name: jupyter-book
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-book/jupyter_book-{{ version }}.tar.gz
  sha256: 143d7cf5adab5f370f3998c51e3495fc92d8d2a78631483adc0cb46a34e3240c

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - jb = jupyter_book.cli.main:main
    - jupyter-book = jupyter_book.cli.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >1.10.0
  run:
    - click >=7.1,<9
    - jinja2
    - jsonschema <5
    - linkify-it-py >=2,<3
    - myst-nb >=1.0,<2.0
    - myst-parser >=3.0,<4.0
    - python >={{ python_min }}
    - pyyaml
    - sphinx >=7,<8
    - sphinx-book-theme >=1.1,<2.0
    - sphinx-comments >=0.0,<1.0
    - sphinx-copybutton >=0.5,<1.0
    - sphinx-design >=0.6,<1.0
    - sphinx-external-toc >=1.0,<2.0
    - sphinx-jupyterbook-latex >=1.0,<2.0
    - sphinx-multitoc-numbering >=0.1,<1.0
    - sphinx-thebe >=0.3,<1.0
    - sphinx-togglebutton >=0.3,<1.0
    - sphinxcontrib-bibtex >=2.5,<3.0
    # undeclared
    - importlib-metadata >=4.8.3

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - jupyter_book
  commands:
    - pip check
    - jb --version
    - jb --help
    - jupyter-book --version
    - jupyter-book --help

about:
  home: https://executablebooks.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    Jupyter Book: Create an online book with Jupyter Notebooks
  dev_url: https://github.com/executablebooks/jupyter-book
  doc_url: https://jupyterbook.org
  doc_source_url: https://github.com/executablebooks/jupyter-book/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - agoose77
    - bollwyvl
    - AakashGfude
