{% set version = "1.0.0" %}
{% set min_python = "python >=3.9" %}

package:
  name: jupyter-book
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-book/jupyter_book-{{ version }}.tar.gz
  sha256: 539c5d0493546200d9de27bd4b5f77eaea03115f8937f825d4ff82b3801a987e
  patches:
    - 0000-use-py312-entry-point-group.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - jb = jupyter_book.cli.main:main
    - jupyter-book = jupyter_book.cli.main:main

requirements:
  host:
    - {{ min_python }}
    - flit-core >=3.5,<4
    - pip
  run:
    - {{ min_python }}
    - click >=7.1,<9
    - jinja2
    - jsonschema <5
    - linkify-it-py >=2,<3
    - myst-nb >=1,<3
    - myst-parser >=1,<3
    - pyyaml
    - sphinx >=5,<8
    - sphinx-book-theme >=1.1.0,<2
    - sphinx-comments
    - sphinx-copybutton
    - sphinx-design >=0.5,<1
    - sphinx-external-toc >=1.0.1,<2
    - sphinx-jupyterbook-latex >=1,<2
    - sphinx-multitoc-numbering >=0.1.3,<1
    - sphinx-thebe >=0.3,<1
    - sphinx-togglebutton
    - sphinxcontrib-bibtex >=2.5.0,<3
    # dep added by patch
    - importlib-metadata >=4.8.3

test:
  imports:
    - jupyter_book
  commands:
    - pip check
    - jb --version
    - jb --help
    - jupyter-book --version
    - jupyter-book --help
  requires:
    - pip

about:
  home: https://executablebooks.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    Jupyter Book: Create an online book with Jupyter Notebooks
  dev_url: https://github.com/executablebooks/jupyter-book
  doc_url: https://jupyterbook.org
  doc_source_url: https://github.com/executablebooks/jupyter-book/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - moorepants
    - bollwyvl
    - AakashGfude
