{% set version = "0.13.2" %}

package:
  name: jupyter-book
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-book/jupyter-book-{{ version }}.tar.gz
  sha256: c09598d2d06b94290e1437c6652e315afbfceec3a5cab365ddf886aa06b2a93b

build:
  number: 0
  entry_points:
    - jb = jupyter_book.cli.main:main
    - jupyter-book = jupyter_book.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed

requirements:
  host:
    - flit-core >=3.5,<4
    - pip
    - python >=3.7
  run:
    - click >=7.1,<9
    - docutils >=0.15,<0.18
    - jinja2
    - jsonschema <5
    - linkify-it-py >=2.0.0,<2.1.0
    - myst-nb >=0.13.1,<0.14.0
    - python >=3.7
    - pyyaml
    - sphinx >=4,<5
    - sphinx-book-theme >=0.3.2,<0.4.0
    - sphinx-comments
    - sphinx-copybutton
    - sphinx-design >=0.1.0,<0.2.0
    - sphinx-external-toc >=0.3.1,<0.4.0
    - sphinx-jupyterbook-latex >=0.5.2,<0.6.0
    - sphinx-multitoc-numbering >=0.1.3,<0.2.0
    - sphinx-thebe >=0.2.1,<0.3.0
    - sphinx-togglebutton
    - sphinxcontrib-bibtex >=2.2.0,<=2.5.0

test:
  imports:
    - jupyter_book
  commands:
    - pip check
    - jb --version
    - jb --help
    - jupyter-book --version
    - jupyter-book --help
  requires:
    - pip

about:
  home: https://executablebooks.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    Jupyter Book: Create an online book with Jupyter Notebooks
  dev_url: https://github.com/executablebooks/jupyter-book
  doc_url: https://jupyterbook.org
  doc_source_url: https://github.com/executablebooks/jupyter-book/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - choldgraf
    - moorepants
    - bollwyvl
    - AakashGfude
