# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: jupyter-book
  version: "2.0.2"
  python_check_max: "3.14"
  nodejs_min: "20"

package:
  name: jupyter-book
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/jupyter_book-${{ version }}.tar.gz
  sha256: 36e1428ad85a70e500513793edff3be83c4f036f80eb67bb909180914f50094b

build:
  number: 1
  noarch: python
  script:
    env:
      JUPYTER_BOOK_PACKAGE_VARIANT: conda-forge
      content: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyter-book = jupyter_book.__main__:main

requirements:
  host:
    - hatch-deps-selector
    - hatch-jupyter-builder
    - hatch-nodejs-version
    - hatchling
    - nodejs ${{ nodejs_min }}.*
    - pip
    - python ${{ python_min }}.*
  run:
    - ipykernel
    - jupyter_core
    - jupyter_server
    - nodejs >=${{ nodejs_min }}
    - platformdirs >=4.2.2
    - python >=${{ python_min }}

tests:
  - python:
      imports: jupyter_book
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - nodejs ${{ nodejs_min }}.*
        - python ${{ python_min }}.*
    script:
      file: run_test.py

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An opinionated distribution of mystmd
  homepage: https://github.com/jupyter-book/jupyter-book
  documentation: https://jupyterbook.org/stable/get-started/

extra:
  recipe-maintainers:
    - agoose77
    - bollwyvl
    - AakashGfude
