# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.0.0"
  python_check_max: "3.14"

package:
  name: jupyter-book
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-book/jupyter_book-${{ version }}.tar.gz
  sha256: d8cd883fdf02de376f92118aa81329c1e481ca02872369665adaed7dfcabfa99

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyter-book = jupyter_book.__main__:main

requirements:
  host:
    - hatch-deps-selector
    - hatch-nodejs-version
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - ipykernel
    - jupyter_core
    - jupyter_server
    - python >=${{ pyton_min }}

tests:
  - python:
      imports: jupyter_book
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - jupyter-book --version
      - jupyter-book --help

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: An opinionated distribution of mystmd
  homepage: https://github.com/jupyter-book/jupyter-book
  documentation: https://jupyterbook.org/stable/get-started/

extra:
  recipe-maintainers:
    - agoose77
    - bollwyvl
    - AakashGfude
